### PR TITLE
modified the source to run on Mac with tspec

### PR DESCRIPTION
**Pull request by wallymathieu**

### CODE REVIEW

**Comment by grosser** [comment]
:heart: this gem has not seen any love in a long time :D

**Comment by grosser** [comment]
does not work for me locally, can you commit your Gemfile.lock, maybe that helps ...

**Comment by wallymathieu** [comment]
I thought I did not create the pull request. Sorry, I'll fix the tests.

**Comment by grosser** [comment]
no worries, it was broken before too :)

**Pull request merged**
